name: Deploy Development

on:
  push:
    branches: [Development]

jobs:
  deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: dev
      app_name_suffix: -dev
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_DEV }}
      OP_VAULT: ${{ secrets.OP_VAULT_DEV }}
