name: Deploy Production

on:
  push:
    branches: [Production]

jobs:
  deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: prod
      app_name_suffix: -prod
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_PROD }}
      OP_VAULT: ${{ secrets.OP_VAULT_PROD }}
